YEAR="1990"
# echo "GitHub Username: "
# read -r USERNAME
# echo "GitHub Access token: "
# read -r ACCESS_TOKEN

# 我需要自己手动更改
c_date="2021-03-21"
first_gap_between=1
total_gap=$first_gap_between

json_data=$(jq '.L' data.json)
rows=$(echo "$json_data" | jq 'length')
cols=$(echo "$json_data" | jq '.[0] | length')

gap=""
last_one=-1

for ((j=0; j<$cols; j++)); do
  for ((i=0; i<$rows; i++)); do
    current_value=$(echo "$json_data" | jq ".[$i][$j]")
    if [ $current_value -eq 1 ]; then
      if [ $last_one -ge 0 ]; then
        current_gap=$((j * $rows + i - last_one))
        total_gap=$((total_gap + current_gap))
        gap="$gap $total_gap"
      else
        gap=$first_gap_between
      fi
      last_one=$((j * $rows + i))
    fi
  done
done

# 输出结果
echo "gap=($gap)"

# Array of following day offsets
getFollowing=($gap)

# Initialize an empty array to store the following dates
followingDates=()

# Loop through the following day offsets and calculate the dates
for offset in "${getFollowing[@]}"; do
  next_date=$(date -j -v+"$offset"d -f "%Y-%m-%d" "$c_date" +%Y-%m-%d)
  followingDates+=("$next_date")
done

# Print the list of following dates
echo "Input date: $c_date"
echo "Following dates:"
for date in "${followingDates[@]}"; do
  echo "${date}"

  [ -z "$USERNAME" ] && exit 1
  [ -z "$ACCESS_TOKEN" ] && exit 1

  # 使用当前日期时间或循环索引创建唯一目录
  unique_dir="$date"
  [ ! -d $unique_dir ] && mkdir $unique_dir

  cd "${unique_dir}" || exit
  git init
  echo "${YEAR} - Generated by https://github.com/KelvinYou" \
    >README.md
  git add .
  GIT_AUTHOR_DATE="${date}T18:00:00" \
    GIT_COMMITTER_DATE="${date}T18:00:00" \
    git commit -m "feat: build Kelvin You"
  git remote add origin "https://${ACCESS_TOKEN}@github.com/${USERNAME}/${YEAR}.git"
  git branch -M main
  git push -u origin main -f
  cd ..
  rm -rf "${unique_dir}"

done